/* Generated by admin.html. Replace the config.js in the repository root with this file. */
window.SITE = {
  "name": "Shaofeng Liang",
  "portrait": "photo/portrait_web.jpg",
  "email": "sliang118@connect.hkust-gz.edu.cn",
  "lede": "I received  my bachelor’s and master’s degrees from China University of Petroleum (East China), where be advised by Prof. **Chenglizhao Chen**.  In September 2026, I joined **{school}** as a Ph.D student under the supervision of Prof. **Yutao Yue**.\n\nMy research interests lie in **Assistive Robotics**. During my master’s studies, I focused on visual perception for UAVs and multimodal perception. My doctoral research will focus on robotic guide dogs.  I aspire to develop **human-centered embodied AI that advances accessibility, independence, and dignity**. Ultimately, I hope my research can help make independent living and equal participation a reality for more people.\n\nWhat's more, I enjoy translating complex ideas into clear, compelling visuals that make research easier to understand and communicate. I have created figures and visualizations for 30+ research papers. ",
  "school": {
    "name": "HKUST (GZ)",
    "url": "https://hkust-gz.edu.cn",
    "logo": "photo/hkust.png"
  },
  "advisor": {
    "name": "Prof. Yutao Yue",
    "url": "https://facultyprofiles.hkust-gz.edu.cn/faculty-personal-page/YUE-Yutao/yutaoyue"
  },
  "links": [
    {
      "label": "Google Scholar",
      "url": "https://scholar.google.com/citations?user=_xogWXUAAAAJ&hl=zh-CN"
    },
    {
      "label": "GitHub",
      "url": "https://github.com/shawnliang420"
    },
    {
      "label": "DBLP",
      "url": "https://dblp.org/pid/397/1364.html"
    },
    {
      "label": "ORCID",
      "url": "https://orcid.org/0009-0005-8134-2188"
    }
  ],
  "news": {
    "kicker": "News",
    "heading": "Recently",
    "show": 7,
    "items": [
      {
        "date": "Sep 2026",
        "text": "One paper (ABLE) is accepted by **EMNLP 2026 ( Main Oral )**. Congratulations to the collaborators!"
      },
      {
        "date": "Sep 2026",
        "text": "One paper is accepted by **NeurIPS 2026**. Congratulations to Kaishen!"
      },
      {
        "date": "Jul 2026",
        "text": "Three papers are accepted by **ACM MM Main 2026**. Congratulations to the collaborators!"
      },
      {
        "date": "Jul 2026",
        "text": "Talk2PC is accepted by **IEEE TITS**."
      },
      {
        "date": "Jun 2026",
        "text": "Three papers are accepted by ACM MM BNI Track 2026 (1 Oral, 2 Posters). Congratulations to the collaborators!"
      },
      {
        "date": "May 2026",
        "text": "One paper is accepted by **ICML 2026**. Congratulations to Haozhe!"
      },
      {
        "date": "Feb 2026",
        "text": "One paper is accepted by **IEEE TCSVT**. "
      },
      {
        "date": "Jan 2026",
        "text": "One paper (AerialMind) is accepted by **AAAI 2026 (Oral)**. See you in Singapore！"
      },
      {
        "date": "Dec 2025",
        "text": "One paper (CDRMOT) is accepted by **Information Fusion**. "
      }
    ],
    "showAll": true,
    "showAllLabel": "Show all news"
  },
  "research": {
    "kicker": "Research Interests",
    "heading": "Human-centered Embodied Assistive Robots",
    "lede": " Humans and robots can develop aligned representations of their environment and coordinate their actions for safe, intuitive navigation.",
    "category": "Main topic",
    "title": "Human-robot Isomorphic Guide-dog Robot",
    "description": "Build intelligent assistive systems that help people with disabilities navigate the world, exercise greater agency, and participate fully in everyday life.",
    "figure": "figures/fig13.png"
  },
  "papers": {
    "kicker": "Publications",
    "heading": "Papers",
    "show": 6,
    "items": [
      {
        "title": "ABLE: Representing and Mapping LLMs via Attribution-Based Large-model Embedding",
        "authors": "Zirui Wang, Yusen Hou, Shaofeng Liang, Bowen Tian, Yanlin Zhang, Wenshuo Chen, Yutao Yue",
        "venue": "EMNLP Main Oral, 2026",
        "thumb": "figures/emnlp.png",
        "links": [
          {
            "label": "PDF",
            "url": "https://arxiv.org/pdf/2606.07524"
          }
        ]
      },
      {
        "title": "When Efficiency Becomes Fragility: Exploiting Dynamic Routing Vulnerabilities in Adaptive UAV Tracking",
        "authors": "Shaofeng Liang, Runwei Guan, Wenshuo Chen, Jiemin Wu, Bowen Tian, Haozhe Jia, Kaishen Yuan, Songning Lai, Daizong Liu, Yutao Yue",
        "venue": "ACMMM, 2026",
        "thumb": "figures/acmmm1.png",
        "links": [
          {
            "label": "PDF",
            "url": "https://arxiv.org/pdf/2608.03902"
          }
        ]
      },
      {
        "title": "POLARIS: Projection-Orthogonal Least Squares for Robust and Adaptive Inversion in Diffusion Models",
        "authors": "Wenshuo Chen*, Haosen Li*, Shaofeng Liang*, Lei Wang, Haozhe Jia, Kaishen Yuan, Jieming Wu, Bowen Tian, Yutao Yue",
        "venue": "Under Review",
        "thumb": "figures/polaris.png",
        "links": [
          {
            "label": "PDF",
            "url": "https://arxiv.org/pdf/2512.00369"
          }
        ]
      },
      {
        "title": "AerialMind: Towards Referring Multi-Object Tracking in UAV Scenarios",
        "authors": "Chenglizhao Chen, Shaofeng Liang, Runwei Guan, Xiaolou Sun, Haocheng Zhao, Haiyun Jiang, Tao Huang, Henghui Ding, Qing-Long Han",
        "venue": "AAAI Oral, 2026",
        "thumb": "figures/aaai2026.png",
        "links": [
          {
            "label": "PDF",
            "url": "https://arxiv.org/pdf/2511.21053"
          }
        ]
      },
      {
        "title": "Adapting Visual Trackers to Dynamic View Transitions With Shift-View Prompt Tuning",
        "authors": "Chenglizhao Chen; Shaofeng Liang; Luming Li; Mengke Song; Xu Yu; Shanchen Pang",
        "venue": "IEEE TCSVT, 2026",
        "thumb": "figures/TCSVT1.png",
        "links": [
          {
            "label": "PDF",
            "url": "https://ieeexplore.ieee.org/document/11417211"
          }
        ]
      },
      {
        "title": "Cognitive Disentanglement for Referring Multi-Object Tracking",
        "authors": "Shaofeng Liang, Runwei Guan, Wangwang Lian, Daizong Liu, Xiaolou Sun, Dongming Wu, Yutao Yue, Weiping Ding, Hui Xiong",
        "venue": "Information Fusion, 2025",
        "thumb": "figures/DRMOT.png",
        "links": [
          {
            "label": "PDF",
            "url": "#https://www.sciencedirect.com/science/article/pii/S1566253525004221"
          }
        ]
      }
    ]
  },
  "figures": {
    "kicker": "Selected figures",
    "show": 8,
    "heading": "The figures I'm proudest of.",
    "lede": "Every figure in my papers is drawn by me. A few favourites, drifting by. Click any of them to see it at full size.",
    "items": [
      {
        "src": "figures/acmmm1.png",
        "label": "",
        "caption": "When Efficiency Becomes Fragility: Exploiting Dynamic Routing Vulnerabilities in Adaptive UAV Tracking",
        "source": "ACM MM, 2026",
        "tool": "",
        "url": "#"
      },
      {
        "src": "figures/aaai2026.png",
        "label": "",
        "caption": "AerialMind: Towards Referring Multi-Object Tracking in UAV Scenarios",
        "source": "AAAI, 2026",
        "tool": "Figma",
        "url": "#"
      },
      {
        "src": "figures/polaris.png",
        "label": "",
        "caption": "POLARIS: Projection-Orthogonal Least Squares for Robust and Adaptive Inversion in Diffusion Models",
        "source": "",
        "tool": "",
        "url": "#"
      },
      {
        "src": "figures/DRMOT.png",
        "label": "",
        "caption": "Cognitive Disentanglement for Referring Multi-Object Tracking",
        "source": "Information Fusion, 2025",
        "tool": "",
        "url": "#"
      },
      {
        "src": "figures/TCSVT1.png",
        "label": "",
        "caption": "Adapting Visual Trackers to Dynamic View Transitions With Shift-View Prompt Tuning",
        "source": "IEEE TCSVT, 2026",
        "tool": "",
        "url": "#"
      },
      {
        "src": "figures/gallery/daji1.png",
        "label": "",
        "caption": "Before the Body Moves: Learning Anticipatory Joint Intent for Language-Conditioned Humanoid Control",
        "source": "Under Review",
        "tool": "",
        "url": "#"
      },
      {
        "src": "figures/gallery/daji2.png",
        "label": "",
        "caption": "Before the Body Moves: Learning Anticipatory Joint Intent for Language-Conditioned Humanoid Control",
        "source": "Under Review",
        "tool": "",
        "url": "#"
      },
      {
        "src": "figures/gallery/FCS.png",
        "label": "",
        "caption": "GroundTrack: Whole-Body Motion Tracking for Low-Posture\nHumanoid Teleoperation",
        "source": "Under Review",
        "tool": "",
        "url": "#"
      }
    ],
    "offer": {
      "category": "Figures for your paper",
      "title": "Drawing figures is the part of research I enjoy most.",
      "description": "I also draw for other people's papers: pipeline diagrams, result plates, and plots that read at a glance. If yours needs one, send me the draft and the deadline and we can work it out together.",
      "button": "Ask about a figure"
    }
  },
  "collaborators": {
    "kicker": "Collaborators",
    "heading": "People I work with",
    "show": 8,
    "items": [
      {
        "name": "Wenshuo Chen",
        "affiliation": "HKUST (Guangzhou)",
        "url": "https://chatonz.github.io/"
      },
      {
        "name": "Jiemin Wu",
        "affiliation": "HKUST (Guangzhou)",
        "url": "https://scholar.google.com/citations?user=INre9KUAAAAJ&hl=zh-CN"
      },
      {
        "name": "Bowen Tian",
        "affiliation": "HKUST (Guangzhou)",
        "url": "https://scholar.google.com/citations?user=SwhX3JkAAAAJ&hl=zh-CN"
      },
      {
        "name": "Kaishen Yuan",
        "affiliation": "HKUST (Guangzhou)",
        "url": "https://yuankaishen2001.github.io/Kkkkkkyle/"
      },
      {
        "name": "Songning Lai",
        "affiliation": "X-tech",
        "url": "https://xll0328.github.io/"
      },
      {
        "name": "Haozhe Jia",
        "affiliation": "Peking University",
        "url": "https://hxxxz0.github.io/"
      },
      {
        "name": "Runwei Guan",
        "affiliation": "HKUST (Guangzhou)",
        "url": "https://scholar.google.com/citations?user=Fjo72tUAAAAJ&hl=zh-CN"
      },
      {
        "name": "Daizong Liu",
        "affiliation": "Wuhan University",
        "url": "https://scholar.google.com/citations?user=lUw7tVIAAAAJ&hl=zh-CN"
      },
      {
        "name": "Sijia Chen",
        "affiliation": "Huazhong University of Science and Technology",
        "url": "#"
      }
    ]
  },
  "footer": {
    "slogan": "Leave the barriers behind. Keep the road ahead.",
    "sloganZh": "让障碍留在过去，让路留给未来。",
    "location": "Systems Hub, HKUST (Guangzhou), Nansha",
    "note": "",
    "copyright": "© 2026 Shaofeng Liang"
  },
  "likes": {
    "label": "Like",
    "namespace": "shawnliang420-github-io",
    "key": "likes",
    "wishes": [
      "Accept!"
    ]
  }
};
